

CREATE TABLE USERS(
U_ID NUMBER PRIMARY KEY,
FIRSTNAME VARCHAR2(30) NOT NULL,
LASTNAME VARCHAR2(30) NOT NULL,
USERNAME VARCHAR2(30) UNIQUE NOT NULL,
PASSWORD VARCHAR2(20) NOT NULL
);

-- PK, FK, NN, U, CHECK, DEFAULT
CREATE TABLE ACCOUNTS(
ACC_ID NUMBER PRIMARY KEY,
USER_ID NUMBER NOT NULL,
BALANCE DECIMAL(12,2) NOT NULL,
CONSTRAINT FK_USERID FOREIGN KEY(USER_ID) REFERENCES USERS(U_ID)
);


-- INTRO TO PL/SQL = PROCEDURAL LANGUAGE EXTENSION OF SQL
--  SEQUENCE
CREATE SEQUENCE U_SEQ
START WITH 2500
INCREMENT BY 2;
/
--TRIGGER
CREATE OR REPLACE TRIGGER u_trigger
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
SELECT U_SEQ.NEXTVAL INTO :new.u_id FROM DUAL;
END;

/

--  SEQUENCE
CREATE SEQUENCE A_SEQ
START WITH 1028
INCREMENT BY 3;
/
--TRIGGER
CREATE OR REPLACE TRIGGER a_trigger
BEFORE INSERT ON ACCOUNTS
FOR EACH ROW
BEGIN
SELECT A_SEQ.NEXTVAL INTO :new.ac_id FROM DUAL;
END;




-- TESTING DML
INSERT INTO USERS(FIRSTNAME, LASTNAME, USERNAME, PASSWORD)
VALUES ('Stark', 'Tony', 'test2', '1231');

INSERT INTO ACCOUNTS( USER_ID, BALANCE)
VALUES ( '22' ,'1200.00');

select * from accounts;
select * from users;

-- Use the Sample HR user to test with
SELECT * FROM v$database;
ALTER USER hr account UNLOCK;
ALTER USER hr IDENTIFIED BY p4ssw0rd;
